services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-exam
    user: root                     # à¹ƒà¸«à¹‰à¹€à¸›à¹‡à¸™à¸«à¸±à¸§à¸«à¸™à¹‰à¸²à¸«à¹‰à¸­à¸‡ (à¹à¸à¹‰ Permission denied)
    privileged: true               # à¹ƒà¸«à¹‰à¸„à¸¸à¸¡ Docker à¹„à¸”à¹‰
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

# ğŸ‘‡ à¸•à¸£à¸‡à¸™à¸µà¹‰à¹à¸«à¸¥à¸°à¸—à¸µà¹ˆà¸«à¸²à¸¢à¹„à¸›! (à¸•à¹‰à¸­à¸‡à¸Šà¸´à¸”à¸‹à¹‰à¸²à¸¢à¸ªà¸¸à¸” à¸«à¹‰à¸²à¸¡à¸¡à¸µà¸¢à¹ˆà¸­à¸«à¸™à¹‰à¸²)
volumes:
  jenkins_home: